parameters:
- name: TestFilter
  type: string
- name: TestDlls
  type: string

variables:
- name: BuildConfiguration
  value: release
- name: BuildPlatform
  value: any cpu
- group: Release Automation Suite Variables
- group: Release Automation Suite Variables (Db)
resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/2.0.3
    endpoint: SkillsFundingAgency
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/5.1.2
    endpoint: SkillsFundingAgency
  pipelines:
  - pipeline: das-enterprise-automation-test-suite
    project: Digital Apprenticeship Service
    source: das-enterprise-automation-test-suite
    branch: master
    trigger:
      stages:
      - Deploy_PP

stages:
- template: stage/test.yml
  parameters:
    TestFilter: ${{ parameters.TestFilter }}
    TestDlls: ${{ parameters.TestDlls }}
- template: stage/test2.yml
  parameters:
    TestFilter: ${{ parameters.TestFilter }}
    TestDlls: ${{ parameters.TestDlls }}
- template: stage/preprod.yml
  parameters:
    TestFilter: ${{ parameters.TestFilter }}
    TestDlls: ${{ parameters.TestDlls }}
  schedule:
  - cron: "15 12 * * 1-5"
    displayName: Daily midnight run
    branches:
      include:
      - master
    always: true