// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SFA.DAS.FlexiPayments.E2ETests.Project.Tests.Features.E2EJourneys.ExisitingUserAccount.Levy
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("FLP_E2E_EUA_01_ExisitingUserAccount")]
    public partial class FLP_E2E_EUA_01_ExisitingUserAccountFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "FLP_E2E_EUA_01_ExisitingUserAccount.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-GB"), "Project/Tests/Features/E2EJourneys/ExisitingUserAccount/Levy", "FLP_E2E_EUA_01_ExisitingUserAccount", "Note that, in the tables below, ULN column is used as a key to store and retrieve" +
                    " ULNs that are used while creating \r\ncommitments through the UI. These are later" +
                    " used to validate data in the commitments and earnings db. ", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("FLP_E2E_EUA_01 Employer adds two apprentices details to a cohort and Provider opt" +
            "s them into the pilot")]
        [NUnit.Framework.CategoryAttribute("regression")]
        [NUnit.Framework.CategoryAttribute("e2escenarios")]
        [NUnit.Framework.CategoryAttribute("flexi-payments")]
        public void FLP_E2E_EUA_01EmployerAddsTwoApprenticesDetailsToACohortAndProviderOptsThemIntoThePilot()
        {
            string[] tagsOfScenario = new string[] {
                    "regression",
                    "e2escenarios",
                    "flexi-payments"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("FLP_E2E_EUA_01 Employer adds two apprentices details to a cohort and Provider opt" +
                    "s them into the pilot", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 9
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 10
 testRunner.Given("the Employer logins using existing Levy Account", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "ULN_Key",
                            "training_code",
                            "date_of_birth",
                            "start_date_str",
                            "duration_in_months",
                            "agreed_price"});
                table2.AddRow(new string[] {
                            "1",
                            "154",
                            "2004/06/01",
                            "2022/08/05",
                            "11",
                            "15000"});
                table2.AddRow(new string[] {
                            "2",
                            "91",
                            "2004/06/01",
                            "2022/09/05",
                            "11",
                            "18000"});
#line 11
 testRunner.And("Employer adds apprentices to the cohort with the following details", ((string)(null)), table2, "And ");
#line hidden
#line 15
 testRunner.And("the Employer approves the cohort", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 16
 testRunner.And("the provider adds Ulns and Opt the learners into the pilot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 17
 testRunner.When("Provider successfully approves the cohort", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "ULN_Key",
                            "is_pilot",
                            "price_episode_from_date_str",
                            "price_episode_to_date_str",
                            "price_episode_cost"});
                table3.AddRow(new string[] {
                            "1",
                            "true",
                            "2022/08/05",
                            "Null",
                            "15000"});
                table3.AddRow(new string[] {
                            "2",
                            "true",
                            "2022/09/05",
                            "Null",
                            "18000"});
#line 18
 testRunner.Then("validate the following data is created in the commitments database", ((string)(null)), table3, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "ULN_Key",
                            "is_pilot",
                            "actual_start_date_str",
                            "start_date_str",
                            "planned_end_date_str",
                            "agreed_price",
                            "funding_type",
                            "funding_band_maximum"});
                table4.AddRow(new string[] {
                            "1",
                            "true",
                            "2022/08/05",
                            "2022/08/01",
                            "2023/07/01",
                            "15000",
                            "0",
                            "15000"});
                table4.AddRow(new string[] {
                            "2",
                            "true",
                            "2022/09/05",
                            "2022/08/01",
                            "2023/08/01",
                            "18000",
                            "0",
                            "18000"});
#line 22
 testRunner.And("validate the following data in Earnings Apprenticeship database", ((string)(null)), table4, "And ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "ULN_Key",
                            "total_on_program_payment",
                            "monthly_on_program_payment",
                            "number_of_delivery_months"});
                table5.AddRow(new string[] {
                            "1",
                            "12000",
                            "1000",
                            "12"});
                table5.AddRow(new string[] {
                            "2",
                            "14400",
                            "1200",
                            "12"});
#line 26
 testRunner.And("validate the following data is created in the earnings database", ((string)(null)), table5, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
