parameters:
  TestFilter:
  TestDlls:

schedule:
- cron: "0 3 * * 1-5"
  displayName: Daily midnight run
  branches:
    include:
    - master
  always: true

stages:
- stage: Deploy_PP
  dependsOn: []
  displayName: Run test suite on PP
  variables:
  - group: PreProd Shared Resources
  - group: PreProd Automation Suite Variables
  - group: PREPROD Automation Suite Variables (Db)
  jobs:
  - schedule:
    - cron: "0 3 * * 1-5"
      displayName: Daily midnight run
      branches:
        include:
        - master
      always: true
  - template: ../job/test-api.yml
    parameters:
      Environment: PP
      ServiceConnection: SFA-DIG-PreProd-ARM
      TestFilter: ${{ parameters.TestFilter }}
      TestDlls: ${{ parameters.TestDlls }}