stages:
- stage: Deploy_TEST
  dependsOn: []
  displayName: Run test suite on TEST
  variables:  
  - group: TEST Automation Suite Variables
  - group: TEST DevTest Shared Resources
  jobs:
  - template: ../job/test-api.yml
    parameters:
      Environment: TEST
      ServiceConnection: SFA-DAS-DevTest-ARM
      TestCategory: ${{ parameters.TestCategory }}
      TestDlls: ${{ parameters.TestDlls }}