Feature: AC_RP_02_ValidatePasswordResetMismatchForPersonalDetailsPendingAccount

@apprenticecommitments
@regression
@deletecmaddatacreatedthroughapi
Scenario: AC_RP_02_ValidatePasswordResetMismatchForPersonalDetailsPendingAccount
	When an apprentice submits Email to reset password for a new account pending personal details confirmation
	Then an error is shown for entering mismatched reset passwords