Feature: EPR_06_ProviderRequestsEmployerAcceptsCreateAccountChangeNameChangePermissions

@addlevyfunds
@createemployeraccount
@singleorgaorn
@regression
@providerleadregistration
@employerproviderrelationships
@deleterequest
Scenario: EPR_06_ProviderAbletoChangeNameChangePermissionsAndEmployerAbleToUpdateNameWhileCreatingAccount
	Given a provider requests employer to create account with ChangeName NoToRecruit YesRecruitApprenticeButWithEmployerReview
    Then the employer accepts the create account request