// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
<<<<<<<< HEAD:src/SFA.DAS.FlexiPayments.E2ETests/Project/Tests/Features/ProviderFeatures/FLP_AIER_01_ValidateEarnings.feature.cs
namespace SFA.DAS.FlexiPayments.E2ETests.Project.Tests.Features.ProviderFeatures
========
namespace SFA.DAS.EmployerAccounts.APITests.Project.Tests.Features.EmployerAccountsLegacyApi
>>>>>>>> master:src/SFA.DAS.EmployerAccounts.APITests/Project/Tests/Features/EmployerAccountsLegacyApi/EMPACC_EAS_API_5_GetEmployerAgreement.feature.cs
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
<<<<<<<< HEAD:src/SFA.DAS.FlexiPayments.E2ETests/Project/Tests/Features/ProviderFeatures/FLP_AIER_01_ValidateEarnings.feature.cs
    [NUnit.Framework.DescriptionAttribute("FLP_AIER_01_ValidateEarnings")]
    public partial class FLP_AIER_01_ValidateEarningsFeature
========
    [NUnit.Framework.DescriptionAttribute("GetEmployerAgreement")]
    public partial class GetEmployerAgreementFeature
>>>>>>>> master:src/SFA.DAS.EmployerAccounts.APITests/Project/Tests/Features/EmployerAccountsLegacyApi/EMPACC_EAS_API_5_GetEmployerAgreement.feature.cs
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
<<<<<<<< HEAD:src/SFA.DAS.FlexiPayments.E2ETests/Project/Tests/Features/ProviderFeatures/FLP_AIER_01_ValidateEarnings.feature.cs
#line 1 "FLP_AIER_01_ValidateEarnings.feature"
========
#line 1 "EMPACC_EAS_API_5_GetEmployerAgreement.feature"
>>>>>>>> master:src/SFA.DAS.EmployerAccounts.APITests/Project/Tests/Features/EmployerAccountsLegacyApi/EMPACC_EAS_API_5_GetEmployerAgreement.feature.cs
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
<<<<<<<< HEAD:src/SFA.DAS.FlexiPayments.E2ETests/Project/Tests/Features/ProviderFeatures/FLP_AIER_01_ValidateEarnings.feature.cs
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-GB"), "Project/Tests/Features/ProviderFeatures", "FLP_AIER_01_ValidateEarnings", null, ProgrammingLanguage.CSharp, featureTags);
========
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-GB"), "Project/Tests/Features/EmployerAccountsLegacyApi", "GetEmployerAgreement", null, ProgrammingLanguage.CSharp, featureTags);
>>>>>>>> master:src/SFA.DAS.EmployerAccounts.APITests/Project/Tests/Features/EmployerAccountsLegacyApi/EMPACC_EAS_API_5_GetEmployerAgreement.feature.cs
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
<<<<<<<< HEAD:src/SFA.DAS.FlexiPayments.E2ETests/Project/Tests/Features/ProviderFeatures/FLP_AIER_01_ValidateEarnings.feature.cs
        [NUnit.Framework.DescriptionAttribute("FLP_AIER_01 Validate Apps indicative earnings report")]
        [NUnit.Framework.CategoryAttribute("regression")]
        [NUnit.Framework.CategoryAttribute("flexi-payments")]
        public void FLP_AIER_01ValidateAppsIndicativeEarningsReport()
========
        [NUnit.Framework.DescriptionAttribute("EMPACC_EAS_API_5_GetEmployerAgreement")]
        [NUnit.Framework.CategoryAttribute("api")]
        [NUnit.Framework.CategoryAttribute("employeraccountsapi")]
        [NUnit.Framework.CategoryAttribute("regression")]
        [NUnit.Framework.CategoryAttribute("innerapi")]
        public void EMPACC_EAS_API_5_GetEmployerAgreement()
>>>>>>>> master:src/SFA.DAS.EmployerAccounts.APITests/Project/Tests/Features/EmployerAccountsLegacyApi/EMPACC_EAS_API_5_GetEmployerAgreement.feature.cs
        {
            string[] tagsOfScenario = new string[] {
                    "api",
                    "employeraccountsapi",
                    "regression",
<<<<<<<< HEAD:src/SFA.DAS.FlexiPayments.E2ETests/Project/Tests/Features/ProviderFeatures/FLP_AIER_01_ValidateEarnings.feature.cs
                    "flexi-payments"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("FLP_AIER_01 Validate Apps indicative earnings report", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 5
========
                    "innerapi"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("EMPACC_EAS_API_5_GetEmployerAgreement", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
>>>>>>>> master:src/SFA.DAS.EmployerAccounts.APITests/Project/Tests/Features/EmployerAccountsLegacyApi/EMPACC_EAS_API_5_GetEmployerAgreement.feature.cs
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
<<<<<<<< HEAD:src/SFA.DAS.FlexiPayments.E2ETests/Project/Tests/Features/ProviderFeatures/FLP_AIER_01_ValidateEarnings.feature.cs
#line 7
testRunner.Given("the provider logs into their account", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 8
testRunner.When("provider is on Apps indicative earnings report page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 9
testRunner.Then("validate correct earnings numbers are displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
========
#line 8
 testRunner.Then("endpoint api/accounts/{hashedAccountId}/legalEntities/{publicHashedLegalEntityId}" +
                        "/agreements/{hashedAgreementId}/agreement from legacy accounts api can be access" +
                        "ed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
>>>>>>>> master:src/SFA.DAS.EmployerAccounts.APITests/Project/Tests/Features/EmployerAccountsLegacyApi/EMPACC_EAS_API_5_GetEmployerAgreement.feature.cs
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
