PRINT CONCAT('Accountid - ', @accountid);
PRINT 'delete from History';
delete h from dbo.History h inner join Commitment c on h.CommitmentId = c.Id and c.EmployerAccountId = @accountid;
PRINT 'delete from Message';
delete m from dbo.[Message] m inner join Commitment c on m.CommitmentId = c.id and c.EmployerAccountId = @accountid;
PRINT 'delete from BulkUpload';
delete b from dbo.BulkUpload b inner join Commitment c on b.CommitmentId = c.id and c.EmployerAccountId = @accountid;
PRINT 'delete from CustomProviderPaymentPriority';
delete from dbo.CustomProviderPaymentPriority where EmployerAccountId = @accountid;
PRINT 'delete from ChangeOfPartyRequest';
delete r from dbo.ChangeOfPartyRequest r inner join AccountLegalEntities l on l.AccountId = @accountid;
PRINT 'delete from PriceHistory';
delete p from dbo.PriceHistory p inner join Apprenticeship a on p.ApprenticeshipId = a.id inner join Commitment c on a.CommitmentId = c.id and c.EmployerAccountId = @accountid;
PRINT 'delete from Relationship';
delete from dbo.Relationship where EmployerAccountId = @accountid;
PRINT 'delete from TransferRequest';
delete t from dbo.TransferRequest t inner join Commitment c on t.CommitmentId = c.id and c.EmployerAccountId = @accountid;
PRINT 'delete from DataLockStatus';
delete d from dbo.DataLockStatus d inner join Apprenticeship a on d.ApprenticeshipId = a.id inner join Commitment c on a.CommitmentId = c.id and c.EmployerAccountId = @accountid;
PRINT 'delete from ApprenticeshipUpdate';
delete u from dbo.ApprenticeshipUpdate u inner join Apprenticeship a on u.ApprenticeshipId = a.id inner join Commitment c on a.CommitmentId = c.id and c.EmployerAccountId = @accountid;
PRINT 'delete from Apprenticeship';
delete a from dbo.Apprenticeship a inner join Commitment c on a.CommitmentId = c.id and c.EmployerAccountId = @accountid;
PRINT 'delete from Commitment';
delete from dbo.Commitment where EmployerAccountId = @accountid;
PRINT 'delete from AccountLegalEntities';
delete from dbo.AccountLegalEntities where AccountId = @accountid;
PRINT 'delete from Accounts';
delete from dbo.Accounts where Id = @accountid;