// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SFA.DAS.RoatpAdmin.UITests.Project.Tests.Features.Outcome
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("RP_AD_OUTCOME_01")]
    public partial class RP_AD_OUTCOME_01Feature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "RP_AD_OUTCOME_01.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-GB"), "Project/Tests/Features/Outcome", "RP_AD_OUTCOME_01", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("RP_AD_OUTCOME_01A Complete Outcome of a Company type Application via Main provide" +
            "r route")]
        [NUnit.Framework.CategoryAttribute("roatp")]
        [NUnit.Framework.CategoryAttribute("rpadoutcome01")]
        [NUnit.Framework.CategoryAttribute("roatpadmin")]
        [NUnit.Framework.CategoryAttribute("roatpoutcome")]
        [NUnit.Framework.CategoryAttribute("newroatpadmin")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public void RP_AD_OUTCOME_01ACompleteOutcomeOfACompanyTypeApplicationViaMainProviderRoute()
        {
            string[] tagsOfScenario = new string[] {
                    "roatp",
                    "rpadoutcome01",
                    "roatpadmin",
                    "roatpoutcome",
                    "newroatpadmin",
                    "regression"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("RP_AD_OUTCOME_01A Complete Outcome of a Company type Application via Main provide" +
                    "r route", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 9
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 10
 testRunner.Given("the admin lands on the Dashboard", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 11
 testRunner.And("the application with PASS outcome is ready to be assessed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 12
 testRunner.When("the oversight user selects the overall application outcome as Successful", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 13
 testRunner.Then("Verify the application is transitioned to Oversight Outcome tab with SUCCESSFUL s" +
                        "tatus", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 14
 testRunner.Then("verify the provider is added to the register with status of Onboarding", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 15
 testRunner.And("verify the Application successful page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("RP_AD_OUTCOME_01B Complete Outcome of a Company type Application via Main provide" +
            "r route unsuccessful Journey")]
        [NUnit.Framework.CategoryAttribute("roatp")]
        [NUnit.Framework.CategoryAttribute("rpadoutcome01")]
        [NUnit.Framework.CategoryAttribute("roatpadmin")]
        [NUnit.Framework.CategoryAttribute("roatpoutcome")]
        [NUnit.Framework.CategoryAttribute("newroatpadmin")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public void RP_AD_OUTCOME_01BCompleteOutcomeOfACompanyTypeApplicationViaMainProviderRouteUnsuccessfulJourney()
        {
            string[] tagsOfScenario = new string[] {
                    "roatp",
                    "rpadoutcome01",
                    "roatpadmin",
                    "roatpoutcome",
                    "newroatpadmin",
                    "regression"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("RP_AD_OUTCOME_01B Complete Outcome of a Company type Application via Main provide" +
                    "r route unsuccessful Journey", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 25
testRunner.Given("the admin lands on the Dashboard", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 26
testRunner.And("the application with PASS outcome is ready to be assessed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 27
testRunner.When("the oversight user overturns gateway and moderation outcome", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 28
testRunner.And("the oversight user selects the overall application outcome as Unsuccessful", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 29
testRunner.Then("Verify the application is transitioned to Oversight Outcome tab with UNSUCCESSFUL" +
                        " status", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 30
testRunner.And("verify the provider is not added to the register", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 31
testRunner.And("verify the Application unsuccessful page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("RP_AD_OUTCOME_01BA Complete Outcome of a Company type Application via Main provid" +
            "er route Appeal Journey")]
        [NUnit.Framework.CategoryAttribute("roatp")]
        [NUnit.Framework.CategoryAttribute("rpadoutcome01")]
        [NUnit.Framework.CategoryAttribute("roatpadmin")]
        [NUnit.Framework.CategoryAttribute("roatpoutcome")]
        [NUnit.Framework.CategoryAttribute("oldroatpadmin")]
        [NUnit.Framework.CategoryAttribute("newroatpadmin")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public void RP_AD_OUTCOME_01BACompleteOutcomeOfACompanyTypeApplicationViaMainProviderRouteAppealJourney()
        {
            string[] tagsOfScenario = new string[] {
                    "roatp",
                    "rpadoutcome01",
                    "roatpadmin",
                    "roatpoutcome",
                    "oldroatpadmin",
                    "newroatpadmin",
                    "regression"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("RP_AD_OUTCOME_01BA Complete Outcome of a Company type Application via Main provid" +
                    "er route Appeal Journey", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 41
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 42
testRunner.Given("the Main provider is already on the RoATP register as Active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 43
testRunner.And("the admin navigates to the Dashboard", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 44
testRunner.And("the application with PASS outcome is ready to be assessed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 45
testRunner.When("the oversight user overturns gateway and moderation outcome", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 46
testRunner.And("the oversight user selects the overall application outcome as Unsuccessful", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 47
testRunner.Given("the application with UNSUCCESSFUL outcome is ready to be assessed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("RP_AD_OUTCOME_01C Complete Outcome of a Company type Application via Main provide" +
            "r route In Progress Journey")]
        [NUnit.Framework.CategoryAttribute("roatp")]
        [NUnit.Framework.CategoryAttribute("rpadoutcome01")]
        [NUnit.Framework.CategoryAttribute("roatpadmin")]
        [NUnit.Framework.CategoryAttribute("roatpoutcome")]
        [NUnit.Framework.CategoryAttribute("newroatpadmin")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public void RP_AD_OUTCOME_01CCompleteOutcomeOfACompanyTypeApplicationViaMainProviderRouteInProgressJourney()
        {
            string[] tagsOfScenario = new string[] {
                    "roatp",
                    "rpadoutcome01",
                    "roatpadmin",
                    "roatpoutcome",
                    "newroatpadmin",
                    "regression"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("RP_AD_OUTCOME_01C Complete Outcome of a Company type Application via Main provide" +
                    "r route In Progress Journey", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 57
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 58
testRunner.Given("the admin lands on the Dashboard", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 59
testRunner.And("the application with PASS outcome is ready to be assessed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 60
testRunner.When("the oversight user selects the overall application outcome as In Progress", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 61
testRunner.Then("Verify the application is transitioned to Oversight Outcome tab with IN PROGRESS " +
                        "status", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 62
testRunner.And("verify the provider is not added to the register", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 63
testRunner.And("verify the Application in progress page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 64
testRunner.Given("the admin navigates to the Dashboard", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 65
testRunner.And("the application with IN PROGRESS outcome is ready to be assessed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 66
testRunner.When("the oversight user selects the overall application outcome as Successful", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 67
testRunner.Then("Verify the application is transitioned to Oversight Outcome tab with SUCCESSFUL s" +
                        "tatus", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 68
testRunner.Then("verify the provider is added to the register with status of Onboarding", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("RP_AD_OUTCOME_01D Complete Outcome of a Company type Application via Main provide" +
            "r route Successful already active Journey")]
        [NUnit.Framework.CategoryAttribute("roatp")]
        [NUnit.Framework.CategoryAttribute("rpadoutcome01")]
        [NUnit.Framework.CategoryAttribute("roatpadmin")]
        [NUnit.Framework.CategoryAttribute("roatpoutcome")]
        [NUnit.Framework.CategoryAttribute("oldroatpadmin")]
        [NUnit.Framework.CategoryAttribute("newroatpadmin")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public void RP_AD_OUTCOME_01DCompleteOutcomeOfACompanyTypeApplicationViaMainProviderRouteSuccessfulAlreadyActiveJourney()
        {
            string[] tagsOfScenario = new string[] {
                    "roatp",
                    "rpadoutcome01",
                    "roatpadmin",
                    "roatpoutcome",
                    "oldroatpadmin",
                    "newroatpadmin",
                    "regression"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("RP_AD_OUTCOME_01D Complete Outcome of a Company type Application via Main provide" +
                    "r route Successful already active Journey", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 78
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 79
testRunner.Given("the Main provider is already on the RoATP register as Active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 80
testRunner.And("the admin navigates to the Dashboard", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 81
testRunner.And("the application with PASS outcome is ready to be assessed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 82
testRunner.When("the oversight user selects the overall application outcome as Successful already " +
                        "active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 83
testRunner.Then("Verify the application is transitioned to Oversight Outcome tab with SUCCESSFUL s" +
                        "tatus", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 84
testRunner.Then("verify the provider is added to the register with Application determined date upd" +
                        "ated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 85
testRunner.And("verify the Application successful page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("RP_AD_OUTCOME_01E Complete Outcome of a Company type Application via Main provide" +
            "r route Successful fitness for funding Journey")]
        [NUnit.Framework.CategoryAttribute("roatp")]
        [NUnit.Framework.CategoryAttribute("rpadoutcome01")]
        [NUnit.Framework.CategoryAttribute("roatpadmin")]
        [NUnit.Framework.CategoryAttribute("roatpoutcome")]
        [NUnit.Framework.CategoryAttribute("oldroatpadmin")]
        [NUnit.Framework.CategoryAttribute("newroatpadmin")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public void RP_AD_OUTCOME_01ECompleteOutcomeOfACompanyTypeApplicationViaMainProviderRouteSuccessfulFitnessForFundingJourney()
        {
            string[] tagsOfScenario = new string[] {
                    "roatp",
                    "rpadoutcome01",
                    "roatpadmin",
                    "roatpoutcome",
                    "oldroatpadmin",
                    "newroatpadmin",
                    "regression"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("RP_AD_OUTCOME_01E Complete Outcome of a Company type Application via Main provide" +
                    "r route Successful fitness for funding Journey", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 95
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 96
testRunner.Given("the Main provider is already on the RoATP register as Active But No Apprentice", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 97
testRunner.And("the admin navigates to the Dashboard", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 98
testRunner.And("the application with PASS outcome is ready to be assessed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 99
testRunner.When("the oversight user selects the overall application outcome as Successful fitness " +
                        "for funding", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 100
testRunner.Then("Verify the application is transitioned to Oversight Outcome tab with SUCCESSFUL s" +
                        "tatus", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 101
testRunner.Then("verify the provider is added to the register with Application determined date upd" +
                        "ated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 102
testRunner.And("verify the Application successful page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
