jobs:
- job: CodeBuild
  pool:
    name: DAS - Continuous Integration Agents
  variables:
    - group: BUILD Management Resources
  workspace:
    clean: all
  steps:
    # DEBUG DIRECTORY TREE
    - script: |
        echo "==== DEBUG: $(Build.SourcesDirectory) (Top Level) ===="
        dir "$(Build.SourcesDirectory)"
        echo ""
        echo "==== DEBUG: $(Build.SourcesDirectory)\das-platform-automation ===="
        dir "$(Build.SourcesDirectory)\das-platform-automation"
        echo ""
        echo "==== DEBUG: $(Build.SourcesDirectory)\das-platform-automation\Infrastructure-Scripts ===="
        dir "$(Build.SourcesDirectory)\das-platform-automation\Infrastructure-Scripts"
        echo ""
        echo "==== DEBUG: $(System.DefaultWorkingDirectory) (Top Level) ===="
        dir "$(System.DefaultWorkingDirectory)"
        echo ""
        echo "==== DEBUG: $(System.DefaultWorkingDirectory)\das-platform-automation ===="
        dir "$(System.DefaultWorkingDirectory)\das-platform-automation"
        echo ""
        echo "==== DEBUG: $(System.DefaultWorkingDirectory)\das-platform-automation\Infrastructure-Scripts ===="
        dir "$(System.DefaultWorkingDirectory)\das-platform-automation\Infrastructure-Scripts"
        echo ""
        echo "==== DEBUG: $(Build.ArtifactStagingDirectory) (Top Level) ===="
        dir "$(Build.ArtifactStagingDirectory)"
      displayName: "DEBUG: List All Relevant Directories At Start"

    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        projects: 'src/**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet pack'
      inputs:
        command: 'pack'
        projects: 'src/**/*.csproj'
        packDirectory: '$(build.artifactstagingdirectory)/publish'
        arguments: '--configuration $(buildConfiguration) --no-restore'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet publish'
      inputs:
        command: publish
        publishWebProjects: false
        zipAfterPublish: false
        projects: 'src/**/*Tests.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/tests --no-restore --no-build'

    - task: CopyFiles@2
      displayName: 'Copy plain files to: $(build.artifactstagingdirectory)/tests/files'
      inputs:
        Contents: |
         src/**/*.sql
         src/**/html2canvas.js
         src/**/appsettings.Config.json
         src/**/appsettings.AdminConfig.json
         src/**/appsettings.ProviderConfig.json
         src/**/appsettings.TimeOutConfig.json
         src/**/appsettings.TestExecution.json
         src/**/appsettings.NServiceBusConfig.json
         src/**/appsettings.BrowserStack.json
         src/**/appsettings.ApiFramework.json
        TargetFolder: '$(build.artifactstagingdirectory)/tests/files'
        flattenFolders: true
        OverWrite: true

    - task: CopyFiles@2
      displayName: 'Copy project json files to: $(build.artifactstagingdirectory)/tests/'
      inputs:
        Contents: |
         src/**/appsettings.Project.json
        TargetFolder: '$(build.artifactstagingdirectory)/tests/'
        flattenFolders: false
        OverWrite: true

    - task: CopyFiles@2
      displayName: 'Copy Check-TestResults.ps1 to: $(build.artifactstagingdirectory)/publish'
      inputs:
        Contents: |
         src/**/Check-TestResults.ps1
        TargetFolder: '$(build.artifactstagingdirectory)/publish'
        OverWrite: true

    - task: CopyFiles@2
      displayName: 'Copy UpdateNoofTestWorkers.ps1 to: $(build.artifactstagingdirectory)/publish'
      inputs:
        Contents: |
         src/**/UpdateNoofTestWorkers.ps1
        TargetFolder: '$(build.artifactstagingdirectory)/publish'
        OverWrite: true

    - task: CopyFiles@2
      displayName: 'Copy runsettings to: $(build.artifactstagingdirectory)/publish/runsettings'
      inputs:
        Contents: |
          src/**/*.runsettings
        TargetFolder: '$(build.artifactstagingdirectory)/publish/runsettings'
        OverWrite: true

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(build.artifactstagingdirectory)/tests'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(build.artifactstagingdirectory)/publish/tests.zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        pathtoPublish: '$(build.artifactstagingdirectory)/publish'
