parameters:
  - name: ServiceConnection
    type: string
  - name: Environment
    type: string

jobs:
- deployment: Deploy_AutomationTests
  displayName: 'Deploy Automation Tests to ${{ parameters.Environment }}'
  environment: ${{ parameters.Environment }}
  pool:
    vmImage: 'windows-latest'
  strategy:
    runOnce:
      deploy:
        steps:
        - task: browserstackcom.browserstack-vsts-extension.browserstack-config-task.BrowserStackConfig@0
          displayName: 'BrowserStack - Configuration'
          inputs:
            BrowserStackServiceEndPoint: 'AS-Browserstack'

        - task: DownloadBuildArtifacts@0
          displayName: 'Download build artifacts'
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.DefaultWorkingDirectory)'

        - script: dir $(System.DefaultWorkingDirectory)\drop
          displayName: 'List drop folder contents'

        - task: ExtractFiles@1
          displayName: 'Extract files'
          inputs:
            archiveFilePatterns: 'drop/tests.zip'
            destinationFolder: '$(System.DefaultWorkingDirectory)/drop/tests'

        - task: TotalALM.totalalm-tokenization.tokenization-build-task.Tokenization@2
          displayName: 'Tokenization: Transform file *.json'
          inputs:
            SourcePath: '$(System.DefaultWorkingDirectory)/drop/tests'
            TargetFileNames: '*.json'

        - task: AzurePowerShell@5
          displayName: "Get Agent's IP Address"
          inputs:
            azureSubscription: ${{ parameters.ServiceConnection }}
            ScriptPath: 'das-platform-automation/Infrastructure-Scripts/Get-MyIpAddress.ps1'
            ScriptArguments: '-WhatsMyIpUrl "https://ifconfig.me/ip"'
            azurePowerShellVersion: LatestVersion

        - task: AzurePowerShell@5
          displayName: "Whitelist agent's IP address"
          inputs:
            azureSubscription: ${{ parameters.ServiceConnection }}
            ScriptPath: 'das-platform-automation/Infrastructure-Scripts/Add-AzSqlIpException.ps1'
            ScriptArguments: '-Name $(System.DefinitionName) -IPAddress $(IPAddress) -ResourceNamePattern $(SharedSQLServerName)'
            azurePowerShellVersion: LatestVersion

        - task: DotNetCoreCLI@2
          displayName: 'Run Browserstack accessibility tests'
          inputs:
            command: test
            projects: |
              $(System.DefaultWorkingDirectory)/drop/tests/**/*.dll
            arguments: '--filter Category=$(TestCategory)'
            testRunTitle: 'Accessibility test $(DATE_TIME)'

        - task: AzurePowerShell@5
          displayName: "SQL - Remove Whitelisted Agent's IP Address"
          inputs:
            azureSubscription: ${{ parameters.ServiceConnection }}
            ScriptPath: 'das-platform-automation/Infrastructure-Scripts/Remove-AzSqlIpException.ps1'
            ScriptArguments: '-Name $(System.DefinitionName) -IPAddress $(IPAddress) -ResourceNamePattern $(SharedSQLServerName)'
            azurePowerShellVersion: LatestVersion
          condition: succeededOrFailed()

        - task: browserstackcom.browserstack-vsts-extension.reports-task.BrowserStackResults@1
          displayName: 'BrowserStack - Results'
