parameters:
  - name: ServiceConnection
    type: string
  - name: Environment
    type: string

jobs:
- deployment: Deploy_AutomationTests
  displayName: 'Deploy Automation Tests to ${{ parameters.Environment }}'
  pool:
    vmImage: 'windows-latest'
  environment: ${{ parameters.Environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          displayName: 'Checkout current branch'

        - checkout: das-platform-automation
          displayName: 'Checkout das-platform-automation templates'

        - task: browserstackcom.browserstack-vsts-extension.browserstack-config-task.BrowserStackConfig@0
          displayName: 'BrowserStack - Configuration'
          inputs:
            BrowserStackServiceEndPoint: 'AS-Browserstack'

        - task: DownloadBuildArtifacts@0
          displayName: 'Download build artifacts'
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.DefaultWorkingDirectory)'

        - task: ExtractFiles@1
          displayName: 'Extract files'
          inputs:
            archiveFilePatterns: 'drop/tests.zip'
            destinationFolder: '$(System.DefaultWorkingDirectory)/drop/tests'

        - task: TotalALM.totalalm-tokenization.tokenization-build-task.Tokenization@2
          displayName: 'Tokenization: Transform file *.json'
          inputs:
            SourcePath: '$(System.DefaultWorkingDirectory)/drop/tests'
            TargetFileNames: '*.json'

        - script: dir $(System.DefaultWorkingDirectory) /S
          displayName: 'List ALL contents in System.DefaultWorkingDirectory (recursive)'

        - script: dir $(Build.SourcesDirectory) /S
          displayName: 'List ALL contents in Build.SourcesDirectory (recursive)'

        - task: AzurePowerShell@5
          displayName: "Get Agent's IP Address"
          inputs:
            azureSubscription: ${{ parameters.ServiceConnection }}
            ScriptType: 'InlineScript'
            Inline: |
              $script = Get-ChildItem -Path "$(Build.SourcesDirectory)" -Recurse -Filter Get-MyIpAddress.ps1 | Select-Object -First 1
              if (-not $script) { throw "Could not find Get-MyIpAddress.ps1 anywhere!" }
              Write-Host "Found script at $($script.FullName)"
              & $script.FullName -WhatsMyIpUrl "https://ifconfig.me/ip"
            azurePowerShellVersion: LatestVersion

        - task: AzurePowerShell@5
          displayName: "Whitelist agent's IP address"
          inputs:
            azureSubscription: ${{ parameters.ServiceConnection }}
            ScriptType: 'InlineScript'
            Inline: |
              $script = Get-ChildItem -Path "$(Build.SourcesDirectory)" -Recurse -Filter Add-AzSqlIpException.ps1 | Select-Object -First 1
              if (-not $script) { throw "Could not find Add-AzSqlIpException.ps1 anywhere!" }
              Write-Host "Found script at $($script.FullName)"
              & $script.FullName -Name "$(System.DefinitionName)" -IPAddress "$(IPAddress)" -ResourceNamePattern "$(SharedSQLServerName)"
            azurePowerShellVersion: LatestVersion

        - task: DotNetCoreCLI@2
          displayName: 'Run ALL Accessibility Tests (Local Agent)'
          inputs:
            command: test
            projects: |
              $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.ApprenticeAmbassadorNetwork.UITests/SFA.DAS.ApprenticeAmbassadorNetwork.UITests.dll
              $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.ApprenticeCommitments.UITests/SFA.DAS.ApprenticeCommitments.UITests.dll
              $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.Approvals.UITests/SFA.DAS.Approvals.UITests.dll
              $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.Campaigns.UITests/SFA.DAS.Campaigns.UITests.dll
              $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.EarlyConnectForms.UITests/SFA.DAS.EarlyConnectForms.UITests.dll
              $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.EmployerFinance.UITests/SFA.DAS.EmployerFinance.UITests.dll
              $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.EmployerProviderRelationships.UITests/SFA.DAS.EmployerProviderRelationships.UITests.dll
              $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.EPAO.UITests/SFA.DAS.EPAO.UITests.dll
              $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.FAA.UITests/SFA.DAS.FAA.UITests.dll
              $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.FAT-V2.UITests/SFA.DAS.FAT-V2.UITests.dll
              $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.FindEPAO.UITests/SFA.DAS.FindEPAO.UITests.dll
              $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.FlexiPayments.E2ETests/SFA.DAS.FlexiPayments.E2ETests.dll
              $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.ManagingStandards.UITests/SFA.DAS.ManagingStandards.UITests.dll
              $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.RAA-V2-Employer.UITests/SFA.DAS.RAA-V2-Employer.UITests.dll
              $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.RAA-V2-Provider.UITests/SFA.DAS.RAA-V2-Provider.UITests.dll
              $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.RAA-V2-QA.UITests/SFA.DAS.RAA-V2-QA.UITests.dll
              $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.RequestApprenticeshipTraining.UITests/SFA.DAS.RequestApprenticeshipTraining.UITests.dll
              $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.Registration.UITests/SFA.DAS.Registration.UITests.dll
              $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.Roatp.UITests/SFA.DAS.Roatp.UITests.dll
              $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.RoatpAdmin.UITests/SFA.DAS.RoatpAdmin.UITests.dll
              $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.SupportConsole.UITests/SFA.DAS.SupportConsole.UITests.dll
              $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.Transfers.UITests/SFA.DAS.Transfers.UITests.dll
              $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.TransferMatching.UITests/SFA.DAS.TransferMatching.UITests.dll
            arguments: '--filter Category=$(TestCategory)'
            testRunTitle: 'Local Accessibility test $(DATE_TIME)'

        - script: |
            echo Listing $(Build.SourcesDirectory) contents
            dir $(Build.SourcesDirectory)
            echo Listing .config subfolder contents
            dir $(Build.SourcesDirectory)\.config
            dotnet tool restore --tool-manifest $(Build.SourcesDirectory)\.config\dotnet-tools.json
          displayName: 'Restore .NET Tools'

        - script: dotnet browserstack-sdk --config browserstack.yml
          displayName: 'Run BrowserStack SDK'
          workingDirectory: $(Build.SourcesDirectory)
          env:
            BROWSERSTACK_USERNAME: $(BROWSERSTACK_USERNAME)
            BROWSERSTACK_ACCESS_KEY: $(BROWSERSTACK_ACCESS_KEY)
            BROWSERSTACK_BUILD_NAME: $(BROWSERSTACK_BUILD_NAME)
            BROWSERSTACK_BUILD_IDENTIFIER: $(BROWSERSTACK_BUILD_IDENTIFIER)

        - task: AzurePowerShell@5
          displayName: "SQL - Remove Whitelisted Agent's IP Address"
          condition: succeededOrFailed()
          inputs:
            azureSubscription: ${{ parameters.ServiceConnection }}
            ScriptType: 'InlineScript'
            Inline: |
              $script = Get-ChildItem -Path "$(Build.SourcesDirectory)" -Recurse -Filter Remove-AzSqlIpException.ps1 | Select-Object -First 1
              if (-not $script) { throw "Could not find Remove-AzSqlIpException.ps1 anywhere!" }
              Write-Host "Found script at $($script.FullName)"
              & $script.FullName -Name "$(System.DefinitionName)" -IPAddress "$(IPAddress)" -ResourceNamePattern "$(SharedSQLServerName)"
            azurePowerShellVersion: LatestVersion

        - task: browserstackcom.browserstack-vsts-extension.reports-task.BrowserStackResults@1
          displayName: 'BrowserStack - Results'
