parameters:
  - name: ServiceConnection
    type: string
  - name: Environment
    type: string

jobs:
- deployment: Deploy_AutomationTests
  displayName: 'Deploy Automation Tests to ${{ parameters.Environment }}'
  pool:
    vmImage: 'windows-latest'
  environment: ${{ parameters.Environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: das-platform-automation
        - task: browserstackcom.browserstack-vsts-extension.browserstack-config-task.BrowserStackConfig@0
          displayName: 'BrowserStack - Configuration'
          inputs:
            BrowserStackServiceEndPoint: 'AS-Browserstack'

        - task: DownloadBuildArtifacts@0
          displayName: 'Download build artifacts'
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.DefaultWorkingDirectory)'

        - task: ExtractFiles@1
          displayName: 'Extract files'
          inputs:
            archiveFilePatterns: 'drop/tests.zip'
            destinationFolder: '$(System.DefaultWorkingDirectory)/drop/tests'

        - task: TotalALM.totalalm-tokenization.tokenization-build-task.Tokenization@2
          displayName: 'Tokenization: Transform file *.json'
          inputs:
            SourcePath: '$(System.DefaultWorkingDirectory)/drop/tests'
            TargetFileNames: '*.json'

        - script: dir $(System.DefaultWorkingDirectory) /S
          displayName: 'List ALL contents in System.DefaultWorkingDirectory (recursive)'

        - task: AzurePowerShell@5
          displayName: "Get Agent's IP Address"
          inputs:
            azureSubscription: ${{ parameters.ServiceConnection }}
            ScriptPath: 'Infrastructure-Scripts/Get-MyIpAddress.ps1'
            ScriptArguments: '-WhatsMyIpUrl "https://ifconfig.me/ip"'
            azurePowerShellVersion: LatestVersion

        - task: AzurePowerShell@5
          displayName: "Whitelist agent's IP address"
          inputs:
            azureSubscription: ${{ parameters.ServiceConnection }}
            ScriptPath: 'Infrastructure-Scripts/Add-AzSqlIpException.ps1'
            ScriptArguments: '-Name $(System.DefinitionName) -IPAddress $(IPAddress) -ResourceNamePattern $(SharedSQLServerName)'
            azurePowerShellVersion: LatestVersion

        - task: DotNetCoreCLI@2
          displayName: 'Run Browserstack accessibility tests'
          inputs:
            command: test
            projects: |
               $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.ApprenticeAmbassadorNetwork.UITests/SFA.DAS.ApprenticeAmbassadorNetwork.UITests.dll
               $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.ApprenticeCommitments.UITests/SFA.DAS.ApprenticeCommitments.UITests.dll
               $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.Approvals.UITests/SFA.DAS.Approvals.UITests.dll
               $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.Campaigns.UITests/SFA.DAS.Campaigns.UITests.dll
               $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.EarlyConnectForms.UITests/SFA.DAS.EarlyConnectForms.UITests.dll
               $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.EmployerFinance.UITests/SFA.DAS.EmployerFinance.UITests.dll
               $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.EmployerProviderRelationships.UITests/SFA.DAS.EmployerProviderRelationships.UITests.dll
               $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.EPAO.UITests/SFA.DAS.EPAO.UITests.dll
               $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.FAA.UITests/SFA.DAS.FAA.UITests.dll
               $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.FAT-V2.UITests/SFA.DAS.FAT-V2.UITests.dll
               $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.FindEPAO.UITests/SFA.DAS.FindEPAO.UITests.dll
               $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.FlexiPayments.E2ETests/SFA.DAS.FlexiPayments.E2ETests.dll
               $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.ManagingStandards.UITests/SFA.DAS.ManagingStandards.UITests.dll
               $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.RAA-V2-Employer.UITests/SFA.DAS.RAA-V2-Employer.UITests.dll
               $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.RAA-V2-Provider.UITests/SFA.DAS.RAA-V2-Provider.UITests.dll
               $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.RAA-V2-QA.UITests/SFA.DAS.RAA-V2-QA.UITests.dll
               $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.RequestApprenticeshipTraining.UITests/SFA.DAS.RequestApprenticeshipTraining.UITests.dll
               $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.Registration.UITests/SFA.DAS.Registration.UITests.dll
               $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.Roatp.UITests/SFA.DAS.Roatp.UITests.dll
               $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.RoatpAdmin.UITests/SFA.DAS.RoatpAdmin.UITests.dll
               $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.SupportConsole.UITests/SFA.DAS.SupportConsole.UITests.dll
               $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.Transfers.UITests/SFA.DAS.Transfers.UITests.dll
               $(System.DefaultWorkingDirectory)/drop/tests/**/SFA.DAS.TransferMatching.UITests/SFA.DAS.TransferMatching.UITests.dll
            arguments: '--filter Category=$(TestCategory)'
            testRunTitle: 'Accessibility test $(DATE_TIME)'

        - task: AzurePowerShell@5
          displayName: "SQL - Remove Whitelisted Agent's IP Address"
          inputs:
            azureSubscription: ${{ parameters.ServiceConnection }}
            ScriptPath: 'Infrastructure-Scripts/Remove-AzSqlIpException.ps1'
            ScriptArguments: '-Name $(System.DefinitionName) -IPAddress $(IPAddress) -ResourceNamePattern $(SharedSQLServerName)'
            azurePowerShellVersion: LatestVersion
          condition: succeededOrFailed()

        - task: browserstackcom.browserstack-vsts-extension.reports-task.BrowserStackResults@1
          displayName: 'BrowserStack - Results'
